# -*- coding: utf-8 -*-
"""Advance time series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arvEQ9wAGBwgkUANqixeSQcJB0T3Wnm3
"""

"""
Advanced Time Series Forecasting with Neural Networks and Explainability

This script implements an end-to-end pipeline:
1) Synthetic complex time series generation (multiple seasonalities + exogenous vars)
2) Train/val/test split and scaling
3) Supervised windowing for deep learning
4) LSTM forecaster with:
   - Time-series-aware cross-validation via rolling-origin splits
   - Simple random-search hyperparameter tuning
5) Statistical baseline using SARIMAX
6) Evaluation using RMSE, SMAPE, MASE
7) Explainability via permutation importance over lag windows
8) Final comparison table + example forecast plot

Dependencies (install if needed):
    pip install numpy pandas matplotlib torch scikit-learn statsmodels
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dataclasses import dataclass
from typing import Tuple, List, Dict

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

import statsmodels.api as sm


RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)


# =========================
# 1. DATA GENERATION
# =========================

def generate_synthetic_time_series(
    n_days: int = 5 * 365,
    freq: str = "D"
) -> pd.DataFrame:
    """
    Generate a univariate time series with:
    - trend
    - weekly and yearly seasonality
    - regime change
    - exogenous variables (temperature-like and promo flag)
    """
    idx = pd.date_range(start="2010-01-01", periods=n_days, freq=freq)
    t = np.arange(n_days)

    # Global trend
    trend = 0.02 * t

    # Yearly and weekly seasonality
    yearly = 10 * np.sin(2 * np.pi * t / 365.25)
    weekly = 3 * np.sin(2 * np.pi * t / 7)

    # Regime change in middle of series
    regime = np.where(t < n_days // 2, 0, 15)

    # Noise
    noise = np.random.normal(loc=0.0, scale=2.5, size=n_days)

    # Exogenous: temperature-like seasonal variable
    temp = 15 + 10 * np.sin(2 * np.pi * (t - 30) / 365.25) + np.random.normal(0, 1.5, n_days)

    # Exogenous: promo flag (occasional 1s)
    promo = (np.random.rand(n_days) < 0.05).astype(float)

    # Target series depends on exogenous vars
    y = 20 + trend + yearly + weekly + regime + 0.5 * temp + 8 * promo + noise

    df = pd.DataFrame(
        {
            "ds": idx,
            "y": y,
            "temp": temp,
            "promo": promo,
        }
    ).set_index("ds")

    return df


# =========================
# 2. PREPROCESSING
# =========================

@dataclass
class DataConfig:
    input_length: int = 60   # number of past days fed into model
    horizon: int = 14        # forecast horizon in days
    test_size: int = 365     # last year for test
    val_size: int = 365      # year for validation before test
    batch_size: int = 64


def train_val_test_split(df: pd.DataFrame, config: DataConfig):
    """
    Split the time series into train/val/test contiguous blocks.
    """
    n = len(df)
    test_start = n - config.test_size
    val_start = n - config.test_size - config.val_size

    df_train = df.iloc[:val_start]
    df_val = df.iloc[val_start:test_start]
    df_test = df.iloc[test_start:]

    return df_train, df_val, df_test


def create_supervised(
    df: pd.DataFrame,
    config: DataConfig,
    scalers: Dict[str, StandardScaler] = None,
    fit_scalers: bool = False
):
    """
    Transform time series into supervised learning format:
    X: [n_samples, input_length, n_features]
    y: [n_samples, horizon]
    Features include lagged target and exogenous variables at each lag step.
    """
    values = df.copy()

    feature_cols = ["y", "temp", "promo"]
    values = values[feature_cols].values.astype(np.float32)

    if scalers is None:
        scalers = {col: StandardScaler() for col in range(values.shape[1])}

    # Apply scaling per feature column
    if fit_scalers:
        for i in range(values.shape[1]):
            scalers[i].fit(values[:, i:i+1])
            values[:, i:i+1] = scalers[i].transform(values[:, i:i+1])
    else:
        for i in range(values.shape[1]):
            values[:, i:i+1] = scalers[i].transform(values[:, i:i+1])

    X, y = [], []
    total_len = config.input_length + config.horizon

    for i in range(len(values) - total_len + 1):
        window = values[i: i + total_len]
        X.append(window[: config.input_length])
        # y is ONLY the target variable "y", which is first column
        y.append(window[config.input_length:, 0])

    X = np.stack(X)  # [n_samples, input_length, n_features]
    y = np.stack(y)  # [n_samples, horizon]

    return X, y, scalers


class TimeSeriesDataset(Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = torch.from_numpy(X).float()
        self.y = torch.from_numpy(y).float()

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# =========================
# 3. LSTM MODEL
# =========================

class LSTMForecaster(nn.Module):
    def __init__(
        self,
        n_features: int,
        hidden_size: int = 64,
        num_layers: int = 2,
        dropout: float = 0.1,
        horizon: int = 14,
    ):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=n_features,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.fc = nn.Linear(hidden_size, horizon)

    def forward(self, x):
        # x: [batch, seq_len, n_features]
        output, (h_n, c_n) = self.lstm(x)
        # Use last hidden state from last layer
        last_hidden = h_n[-1]  # [batch, hidden_size]
        out = self.fc(last_hidden)  # [batch, horizon]
        return out


@dataclass
class TrainingConfig:
    epochs: int = 20
    lr: float = 1e-3
    weight_decay: float = 1e-4
    hidden_size: int = 64
    num_layers: int = 2
    dropout: float = 0.1
    device: str = "cuda" if torch.cuda.is_available() else "cpu"


def train_one_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    data_config: DataConfig,
    train_config: TrainingConfig,
) -> Tuple[LSTMForecaster, Dict[str, List[float]]]:
    """
    Train a single LSTM model and return the trained model + training history.
    """
    device = train_config.device
    n_features = X_train.shape[-1]

    model = LSTMForecaster(
        n_features=n_features,
        hidden_size=train_config.hidden_size,
        num_layers=train_config.num_layers,
        dropout=train_config.dropout,
        horizon=data_config.horizon,
    ).to(device)

    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=train_config.lr,
        weight_decay=train_config.weight_decay,
    )

    train_dataset = TimeSeriesDataset(X_train, y_train)
    val_dataset = TimeSeriesDataset(X_val, y_val)

    train_loader = DataLoader(
        train_dataset,
        batch_size=data_config.batch_size,
        shuffle=True,
        drop_last=False,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=data_config.batch_size,
        shuffle=False,
        drop_last=False,
    )

    history = {"train_loss": [], "val_loss": []}

    for epoch in range(1, train_config.epochs + 1):
        model.train()
        train_losses = []
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            optimizer.zero_grad()
            preds = model(xb)
            loss = criterion(preds, yb)
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())

        # Validation
        model.eval()
        val_losses = []
        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                preds = model(xb)
                loss = criterion(preds, yb)
                val_losses.append(loss.item())

        avg_train = float(np.mean(train_losses))
        avg_val = float(np.mean(val_losses))
        history["train_loss"].append(avg_train)
        history["val_loss"].append(avg_val)

        print(f"Epoch {epoch:03d} | train_loss={avg_train:.4f} | val_loss={avg_val:.4f}")

    return model, history


# =========================
# 4. HYPERPARAMETER TUNING (simple random search + rolling-origin CV)
# =========================

def rolling_origin_splits(
    n_samples: int,
    n_splits: int = 3,
    train_fraction: float = 0.6,
):
    """
    Generate indices for rolling-origin evaluation over supervised samples.
    This operates on the supervised dataset indices (already windowed).
    """
    indices = np.arange(n_samples)
    initial_train_size = int(train_fraction * n_samples)
    remaining = n_samples - initial_train_size
    fold_size = max(1, remaining // n_splits)

    for i in range(n_splits):
        train_end = initial_train_size + i * fold_size
        val_end = train_end + fold_size
        if val_end > n_samples:
            break
        train_idx = indices[:train_end]
        val_idx = indices[train_end:val_end]
        if len(train_idx) == 0 or len(val_idx) == 0:
            continue
        yield train_idx, val_idx


def tune_hyperparameters(
    X: np.ndarray,
    y: np.ndarray,
    data_config: DataConfig,
    n_trials: int = 5,
) -> TrainingConfig:
    """
    Very small random search over hyperparameters using rolling-origin CV.
    You can replace this with more sophisticated Bayesian optimization if desired.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"

    hidden_size_choices = [32, 64, 128]
    num_layers_choices = [1, 2, 3]
    dropout_choices = [0.0, 0.1, 0.3]
    lr_choices = [1e-3, 5e-4]
    weight_decay_choices = [0.0, 1e-4]

    best_cfg = None
    best_score = np.inf

    for trial in range(n_trials):
        cfg = TrainingConfig(
            epochs=10,  # fewer epochs for tuning
            lr=float(np.random.choice(lr_choices)),
            weight_decay=float(np.random.choice(weight_decay_choices)),
            hidden_size=int(np.random.choice(hidden_size_choices)),
            num_layers=int(np.random.choice(num_layers_choices)),
            dropout=float(np.random.choice(dropout_choices)),
            device=device,
        )

        rmses = []
        for train_idx, val_idx in rolling_origin_splits(len(X), n_splits=3):
            X_train, y_train = X[train_idx], y[train_idx]
            X_val, y_val = X[val_idx], y[val_idx]

            model, _ = train_one_model(
                X_train, y_train, X_val, y_val, data_config, cfg
            )

            # Evaluate RMSE on this fold
            model.eval()
            with torch.no_grad():
                X_val_t = torch.from_numpy(X_val).float().to(cfg.device)
                preds = model(X_val_t).cpu().numpy()
            rmse_val = np.sqrt(mean_squared_error(y_val.flatten(), preds.flatten()))
            rmses.append(rmse_val)

        if len(rmses) == 0:
            continue

        avg_rmse = float(np.mean(rmses))
        print(
            f"[TUNING] Trial {trial+1}/{n_trials} | "
            f"hidden={cfg.hidden_size} layers={cfg.num_layers} "
            f"dropout={cfg.dropout} lr={cfg.lr} wd={cfg.weight_decay} "
            f"-> CV RMSE={avg_rmse:.4f}"
        )

        if avg_rmse < best_score:
            best_score = avg_rmse
            best_cfg = cfg

    print(f"Best config from tuning: {best_cfg}")
    return best_cfg


# =========================
# 5. STATISTICAL BASELINE (SARIMAX)
# =========================

def fit_sarimax_baseline(
    df_train: pd.DataFrame,
    df_val: pd.DataFrame,
    order=(1, 1, 1),
    seasonal_order=(1, 1, 1, 7),
):
    """
    Fit a SARIMAX model on train+val and evaluate on val.
    """
    endog_train = df_train["y"]
    exog_train = df_train[["temp", "promo"]]
    endog_val = df_val["y"]
    exog_val = df_val[["temp", "promo"]]

    model = sm.tsa.statespace.SARIMAX(
        endog=endog_train,
        exog=exog_train,
        order=order,
        seasonal_order=seasonal_order,
        enforce_stationarity=False,
        enforce_invertibility=False,
    )
    res = model.fit(disp=False)

    pred = res.get_prediction(
        start=endog_val.index[0],
        end=endog_val.index[-1],
        exog=exog_val,
    )
    yhat = pred.predicted_mean.values
    rmse_val = np.sqrt(mean_squared_error(endog_val.values, yhat))
    print(f"SARIMAX validation RMSE: {rmse_val:.4f}")
    return res


# =========================
# 6. METRICS
# =========================

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


def smape(y_true, y_pred, epsilon=1e-8):
    """
    Symmetric Mean Absolute Percentage Error.
    """
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    denominator = (np.abs(y_true) + np.abs(y_pred) + epsilon) / 2.0
    diff = np.abs(y_true - y_pred) / denominator
    return np.mean(diff) * 100.0


def mase(y_true, y_pred, y_train, m: int = 7):
    """
    Mean Absolute Scaled Error.
    y_train: in-sample training target series used for naive seasonal forecast.
    m: seasonal period (e.g., 7 for weekly seasonality on daily data).
    """
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    y_train = np.asarray(y_train)

    # Denominator: MAE of seasonal naive forecast on training data
    if len(y_train) <= m:
        raise ValueError("y_train length must be greater than seasonal period m.")
    naive_forecast = y_train[m:]
    naive_actual = y_train[:-m]
    mae_naive = np.mean(np.abs(naive_forecast - naive_actual))

    return np.mean(np.abs(y_true - y_pred)) / mae_naive


# =========================
# 7. EXPLAINABILITY: Permutation Importance over lags
# =========================

def compute_permutation_importance_lags(
    model: nn.Module,
    X_val: np.ndarray,
    y_val: np.ndarray,
    base_rmse: float,
    device: str,
) -> pd.DataFrame:
    """
    Permute each lag (time step) in the input sequence and measure increase in RMSE.
    This tells us which past lags are most important.
    """
    model.eval()
    n_samples, input_length, n_features = X_val.shape
    importances = []

    for lag in range(input_length):
        X_perm = X_val.copy()
        # Shuffle the entire feature vector at this lag across samples
        shuffled = np.random.permutation(X_perm[:, lag, :])
        X_perm[:, lag, :] = shuffled

        with torch.no_grad():
            X_t = torch.from_numpy(X_perm).float().to(device)
            preds = model(X_t).cpu().numpy()
        rmse_perm = rmse(y_val.flatten(), preds.flatten())
        delta = rmse_perm - base_rmse
        importances.append({"lag": lag + 1, "rmse": rmse_perm, "delta_rmse": delta})

    df_imp = pd.DataFrame(importances).sort_values("delta_rmse", ascending=False)
    return df_imp


def plot_lag_importances(df_imp: pd.DataFrame):
    plt.figure(figsize=(10, 4))
    plt.bar(df_imp["lag"], df_imp["delta_rmse"])
    plt.xlabel("Lag (days back from forecast origin)")
    plt.ylabel("Increase in RMSE when permuted")
    plt.title("Permutation Importance over Lag Steps")
    plt.tight_layout()
    plt.show()


# =========================
# 8. DRIVER SCRIPT
# =========================

def main():
    # ---- Configs ----
    data_cfg = DataConfig()
    print("Generating synthetic dataset...")
    df = generate_synthetic_time_series()

    # ---- Train/Val/Test split ----
    df_train, df_val, df_test = train_val_test_split(df, data_cfg)
    print(f"Train: {df_train.index[0]} to {df_train.index[-1]} | n={len(df_train)}")
    print(f"Val:   {df_val.index[0]} to {df_val.index[-1]} | n={len(df_val)}")
    print(f"Test:  {df_test.index[0]} to {df_test.index[-1]} | n={len(df_test)}")

    # ---- Supervised transformation ----
    X_train, y_train, scalers = create_supervised(
        df_train, data_cfg, scalers=None, fit_scalers=True
    )
    X_val, y_val, _ = create_supervised(
        df_val, data_cfg, scalers=scalers, fit_scalers=False
    )
    X_test, y_test, _ = create_supervised(
        df_test, data_cfg, scalers=scalers, fit_scalers=False
    )

    print(f"Supervised shapes | X_train: {X_train.shape}, y_train: {y_train.shape}")

    # ---- Hyperparameter tuning on train+val supervised samples ----
    X_tune = np.concatenate([X_train, X_val], axis=0)
    y_tune = np.concatenate([y_train, y_val], axis=0)
    print("Starting hyperparameter tuning (random search with rolling-origin CV)...")
    best_train_cfg = tune_hyperparameters(X_tune, y_tune, data_cfg, n_trials=5)

    # ---- Final train on train+val, evaluate on test ----
    print("Training final LSTM model on train+val...")
    model, history = train_one_model(
        X_tune,
        y_tune,
        X_val,
        y_val,  # still used for monitoring
        data_cfg,
        best_train_cfg,
    )

    device = best_train_cfg.device

    # Predictions on test supervised samples
    model.eval()
    with torch.no_grad():
        X_test_t = torch.from_numpy(X_test).float().to(device)
        y_pred_test = model(X_test_t).cpu().numpy()

    # Flatten for metrics
    y_true_flat = y_test.flatten()
    y_pred_flat = y_pred_test.flatten()

    # y_train_raw for MASE denominator (use original scale training y)
    y_train_raw = df_train["y"].values

    rmse_lstm = rmse(y_true_flat, y_pred_flat)
    smape_lstm = smape(y_true_flat, y_pred_flat)
    mase_lstm = mase(y_true_flat, y_pred_flat, y_train_raw, m=7)

    print(f"LSTM Test RMSE: {rmse_lstm:.4f}")
    print(f"LSTM Test SMAPE: {smape_lstm:.4f}")
    print(f"LSTM Test MASE: {mase_lstm:.4f}")

    # ---- Explainability: Permutation importance on lags ----
    base_rmse = rmse_lstm
    df_imp = compute_permutation_importance_lags(
        model, X_test, y_test, base_rmse, device=device
    )
    print("Top 10 most important lags (by delta RMSE):")
    print(df_imp.head(10).to_string(index=False))
    # Optional visualization:
    # plot_lag_importances(df_imp)

    # ---- Statistical baseline: SARIMAX ----
    print("Fitting SARIMAX baseline...")
    _ = fit_sarimax_baseline(df_train, df_val)

    # Forecasting over test period using SARIMAX (train+val fit)
    df_train_val = pd.concat([df_train, df_val])
    endog_train_val = df_train_val["y"]
    exog_train_val = df_train_val[["temp", "promo"]]

    model_full = sm.tsa.statespace.SARIMAX(
        endog=endog_train_val,
        exog=exog_train_val,
        order=(1, 1, 1),
        seasonal_order=(1, 1, 1, 7),
        enforce_stationarity=False,
        enforce_invertibility=False,
    )
    res_full = model_full.fit(disp=False)

    pred_test = res_full.get_prediction(
        start=df_test.index[0],
        end=df_test.index[-1],
        exog=df_test[["temp", "promo"]],
    )
    sarimax_pred = pred_test.predicted_mean.values

    rmse_sarimax = rmse(df_test["y"].values, sarimax_pred)
    smape_sarimax = smape(df_test["y"].values, sarimax_pred)
    mase_sarimax = mase(
        df_test["y"].values, sarimax_pred, y_train_raw, m=7
    )

    print(f"SARIMAX Test RMSE: {rmse_sarimax:.4f}")
    print(f"SARIMAX Test SMAPE: {smape_sarimax:.4f}")
    print(f"SARIMAX Test MASE: {mase_sarimax:.4f}")

    # ---- Summary table ----
    summary = pd.DataFrame(
        {
            "Model": ["LSTM", "SARIMAX"],
            "RMSE": [rmse_lstm, rmse_sarimax],
            "SMAPE": [smape_lstm, smape_sarimax],
            "MASE": [mase_lstm, mase_sarimax],
        }
    )
    print("\nFinal evaluation metrics on TEST set:")
    print(summary.to_string(index=False))

    # ---- Example forecast plot: LSTM vs SARIMAX vs actual ----
    n_plot = 3  # number of forecast windows to plot
    start_idx = data_cfg.input_length
    end_idx = start_idx + n_plot * data_cfg.horizon

    time_index = df_test.index[start_idx:end_idx]
    actual_series = df_test["y"].values[start_idx:end_idx]

    lstm_series = y_pred_test[:n_plot].reshape(-1)
    sarimax_series = sarimax_pred[start_idx:end_idx]

    plt.figure(figsize=(12, 6))
    plt.plot(time_index, actual_series, label="Actual", linewidth=2)
    plt.plot(time_index, lstm_series, label="LSTM forecast", linestyle="--")
    plt.plot(time_index, sarimax_series, label="SARIMAX forecast", linestyle=":")

    plt.title("Example forecasts on test set")
    plt.xlabel("Date")
    plt.ylabel("Value")
    plt.legend()
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()